### ISSUE TITLE
Unable to add Inspection to Facility or Well

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#10]
I get this 
![image](https://user-images.githubusercontent.com/4369080/56994096-5b54f080-6b5b-11e9-8fea-51964db3ab29.png)

Is Pro 2.4  required to add an inspection record for a facility?  Or is it just needed to check for both Facility_FK and Well_FK

**Comment by steveoh** [comment]
I'd have to research this... and you will have to give me a more detailed process of how you got here. I do not know how the add new row to relationship works. If it creates the inspection record or if the record was already created?

Please proide more details.

**Comment by CanDKD** [comment]
This is the new facility and well I have created.  I want to add a Facility Inspection which should add a Facility_FK to the inspection record.  The image below shows how I do this.  Under the 'ViolationEnforcement Facility'  I right-click on the .....ToInspection and select Add New To Relationship.  This should create a new inspection record with the Facility_FK populated.
![image](https://user-images.githubusercontent.com/4369080/56995940-5fcfd800-6b60-11e9-874e-c2cc5b4e164c.png)

**Comment by CanDKD** [comment]
I have disabled the Constraint.FacilityFk.WellFk attribute rule and I am able to add a facility inspection.  I am not sure what the expression for this rule does, but it looks like maybe it is looking for existing values in the Facility_FK  and the Well_FK.  Referring to the screenshot above, the 'Add New To Relationship' is the same as adding a new record to the Inspection table.  Adding that record in the scenario above would automatically add the Facility_FK.  I am going to try to create a new constraint rule which only triggers on Update to see if this expression will not allow both a Well_FK and a Facility_FK

**Comment by steveoh** [comment]
That is a good idea to keep you moving. We will need to figure this out for insert also as arcpy or other SDK's would then be able to insert a row with both foreign keys.

**Comment by CanDKD** [comment]
Disabling the constraint rule gets me farther down the road but a new constraint AR that only triggers on update didn't work.  Moving on....

**Comment by steveoh** [comment]
Please be more descriptive with our `don't work` comments. What exactly did not work with the update only rule?

**Comment by CanDKD** [comment]
Sorry...I thought it would prevent my adding a Well_FK if the record already had a FAcility_FK.  That was not the case,  I was able to add both and an error was not created.

**Comment by steveoh** [comment]
Are you using the relationship class still? What happens if you copy and paste guids?

**Comment by CanDKD** [comment]
When I copied the Facility GUID to the Facility_FK of an Inspection record already assigned to a Well. I get an error
![image](https://user-images.githubusercontent.com/4369080/57105951-5d4cba00-6ce9-11e9-9a3b-6d00ea013459.png)

**Comment by CanDKD** [comment]
Coping the GUID, revealed the error.  But selecting the Well Inspection record and attempting to add it to the facility as below does not reveal the error.
![image](https://user-images.githubusercontent.com/4369080/57106423-8c176000-6cea-11e9-9649-55691f6dbaf1.png)

**Comment by CanDKD** [comment]
![image](https://user-images.githubusercontent.com/4369080/57106491-bff28580-6cea-11e9-80aa-0eea3b37b64a.png)

**Comment by steveoh** [comment]
OK so the rule sort of works but not when you use the relationship to add the item?

**Comment by CanDKD** [comment]
that's right

**Comment by steveoh** [comment]
ok that might identify a bug

**Comment by CanDKD** [comment]
Using the relationship, is how we have always performed the editing.  But we inevitably end up assigning 2 _FKs instead of just one.

**Comment by CanDKD** [comment]
I am able to create a Facility Inspection record with the following fields populated:  ObjectID, GlobalID, GUID, Facility_FK, NOT the Well_FK, and the CreatedOn, CreatedBy, ModifiedOn, EditedBy  BUT when I attempt to populate the Type of Inspection field, the following error is occurs:
![image](https://user-images.githubusercontent.com/4369080/62071561-0c6e3400-b1fa-11e9-9dad-0bee7ff4c859.png)

**Comment by steveoh** [comment]
I have an open issue with esri for this. 02373545

**Comment by steveoh** [comment]
We have this working as is and I am working with esri to see if it can be improved. If anything comes of it I will create a new issue to improve our rules.
