### ISSUE TITLE
FacilityAddress AR

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#104]
sent you FacilityARs.csv including new AR for 'FacilityAddress.update'  error code 555

**Comment by steveoh** [comment]
i think you can attach files like that here with a drag and drop... or more simply, paste the name and script.

```
if (!haskey($feature, 'FacilityAddress')) {
    return true;
}

return iif(isempty($feature.FacilityAddress), {
    'errorMessage': 'FacilityAddress must not be empty.'
}, true);
```

**Comment by steveoh** [comment]
good catch. I had the address rule in code but was not applying it.
