### ISSUE TITLE
Contact table; OwnerType AR

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#105]
The error does not go away after selecting Owner, Operator, or Owner/Operator

![image](https://user-images.githubusercontent.com/4369080/63957451-a0276000-ca45-11e9-8762-f8efa15b2ad2.png)

**Comment by steveoh** [comment]
please provide the steps you made to reproduce as I thought I tested this successfully

**Comment by CanDKD** [comment]
I have created a new facility - New Test Facility in the screenshot above.  I am in the Attribute pane.  With New Test Facility selected, I right-click on UICContact ; select Add New to Relationship to create a new Contact record.  The record is created.  I enter the Contact Name. Click on the ContactType to select and the error is raised.  It does not go away even after selecting one of the allowable options.

**Comment by steveoh** [comment]
yup, the code is not accounting for the current feature. only the related contacts. Should be a quick fix.
