### ISSUE TITLE
Add 7 new AR rules

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-attribute-rules#108]
They are in the [ar doc](https://docs.google.com/spreadsheets/d/1BIbeMz80a8CDSCjN5PYUlWYCswEjUzZLt3DnlLlWfrI/edit#gid=0)

**Table : Rule Name -- Error Message**

- [x] UICWell : WellName -- WellName must not be empty.
- [x] UICArtPen : ArtPen_CAType.Waiting -- If ArtPen_CADate is populated, ArtPen_CAType should no longer be 'waiting'.
- [x] UICArtPen : ArtPen_CAType.Comment -- If ArtPen_CAType is 'other CA  method', then describe alternate CA method in Comments field.
- [x] UICInspection : InspectionDate.empty -- InspectionDate must not be empty.
- [x] UICMIT : RemediationAction.Waiting --  If MITRemActDate is populated, MITRemediationAction should no longer be 'waiting'
- [ ] UICMIT : Type.comment -- If MITType is '1 - other significant leak test' OR '2 - other fluid migration test', describe the alternative MIT method in Comments field.
- [x] UICViolation : ViolationDate.empty -- ViolationDate may not be empty.

**Comment by CanDKD** [comment]
**Table : Rule Name -- Error Message**

UICWell : WellName -- WellName must not be empty.

UICArtPen : ArtPen_CAType.Waiting -- If ArtPen_CADate is populated, ArtPen_CAType should no longer be 'waiting'.

UICArtPen : ArtPen_CAType.Comment -- If ArtPen_CAType is 'other CA  method', then describe alternate CA method in Comments field.

UICInspection : InspectionDate.empty -- InspectionDate must not be empty.

UICMIT : RemediationAction.Waiting --  If MITRemActDate is populated, MITRemediationAction should no longer be 'waiting'

UICMIT : Type.comment -- If MITType is '1 - other significant leak test' OR '2 - other fluid migration test', describe the alternative MIT method in Comments field.

UICViolation : ViolationDate.empty -- ViolationDate may not be empty.

**Comment by steveoh** [comment]
@candkd, the uicinspection date sort of conflicts with https://github.com/agrc/uic-attribute-rules/blob/master/src/rules/inspection.py#L54 which is https://github.com/agrc/uic-attribute-rules/blob/master/src/rules/arcade/inspection/dateConstraint.js

Do we need to update the existing rule or add another?

**Comment by CanDKD** [comment]
For the WellOperatingStatus tbl we have a constraint AR (OperatingStatusType date requirement) which does not allow the OperatingStatusDate to be empty if OperatingStatusType has a value.  Can't we create a similar constraint AR for the Inspection tbl?  So if InspectionType has a value InspectionDate cannot be empty.  Would that still interfere with L54 of the inspection.py code?
