### ISSUE TITLE
Problem Setting WellClass in UICWell

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#11]
I get this Arcade error when I try to set the Well Class to Class I
![image](https://user-images.githubusercontent.com/4369080/56994662-fd290d00-6b5c-11e9-9bd6-718e87ff182d.png)

**Comment by steveoh** [comment]
You need to set a subclass

**Comment by CanDKD** [comment]
We generally set the Class before the Subclass

**Comment by CanDKD** [comment]
Tried to set Subclass first, got this:
![image](https://user-images.githubusercontent.com/4369080/56994907-9e17c800-6b5d-11e9-98ba-67fdfe000b5c.png)

**Comment by steveoh** [comment]
Set them both before applying the edits

**Comment by CanDKD** [comment]
The errors arise before I apply the edits.

**Comment by CanDKD** [comment]
In order to populate the WellClass and WellSubclass fields, I have had to disable the following three Constraint ARs: Constraint.Well.Class, Constraint.Well.Subclass and Constraint.Well.ClassIFacilityType.  However, I recall we are going to move the ClassIFacilityType field to the UICWell table as it is more relevant to the well rather than the facility.

**Comment by steveoh** [comment]
> The errors arise before I apply the edits.

I think you can ignore the warning and continue to add the other required values. This might be a bug of the attributes pane. If you are in the attribute table the same issue does not arise. 

![image](https://user-images.githubusercontent.com/325813/57240519-e31f7c80-6feb-11e9-942e-66ebfff02280.png)

**Comment by CanDKD** [comment]
I have re-enabled the two Constraint ARs for WellClass and WellSubclass but not the one for ClassIFacilityType.  Populating WellClass first reveals an error for WellSubclass.  Ignoring this and continuing to select the WellSubclass.  The dropdown menu for Subclass shows only the Class I subclasses as we wanted with an option to Show More (the rest of the SubClasses).  Once I have selected the well Subclass and moved my cursor to another field the Apply button is activated and I am then able to save the edits.  So the question is: how to address the error for WellSubclass showing up before we have selected it.

**Comment by steveoh** [comment]
That is the bug report I would like to present to esri. I'll let you know what they say since it is a different behavior in the two windows.

**Comment by steveoh** [comment]
It sounds like the bug I was thinking is actually the intended behavior and the table view has the bug and should act more like the attributes pane. :( I think I can code around this for the case you have above...

**Comment by CanDKD** [comment]
I thought I'd try this again while using ArcPro 2.4 to see if this problem may have been resolved by 2.4.  It hadn't.  I get the same Arcade error above when I try to set the WellClass or WellSubClass irrespective of the order I try to select them.

**Comment by steveoh** [comment]
The error message goes away when both classes are set. It did for me when I was testing #14.
