### ISSUE TITLE
Inadvertently Adding GlobalIDs to a table

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#110]
The Add Global IDs button is just above the Privileges button in Pro.  This is probably how I inadvertently added the Global IDs to the intermediate table.  It would be nice if Pro had a warning box that popped up asking if the user really wanted to add the Global ID especially since you can't delete that field once added.  Possibly something to chat with ESRI about.

**Comment by steveoh** [comment]
Prod has the global id on that table. I think it might be an import issue?

**Comment by CanDKD** [comment]
So in DEV I had to delete the Global ID relationship class between violation and enforcement and create a new one without the Global IDs.  I had to manually populate the intermediate table.  Looking forward, since the PROD intermediate table also has Global IDs, do you think I will have to delete, re-create, populate a new relationship class like I did for DEV?

**Comment by steveoh** [comment]
Wasn't it all a permission issue?

**Comment by CanDKD** [comment]
Yes, it was a permission issue, but the question is why were permissions not set for this xref table when it was for the other one?  The only difference between the two is that the table with the Global IDs didn't get the permissions assigned.

**Comment by steveoh** [comment]
That may be a coincidence... or a bug in pro.

**Comment by steveoh** [comment]
I looked into this issue with esri and the results were that

1. New users should use a separate schema (which michael does but i didn't know)
1. Users need execute privilege
