### ISSUE TITLE
MIT tbl; need a MITRemActDate constraint AR

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#114]
MITRemActDate must be between the MITDate and today's date.  Both of these dates are in the MIT tbl

**Comment by CanDKD** [comment]
I tried adding a new MIT record and got this error.  
![image](https://user-images.githubusercontent.com/4369080/67509588-9474a600-f650-11e9-94c6-5ae7acb57744.png)

**Comment by steveoh** [comment]
Ok, so this needs to be update only. I will fix this.

**Comment by CanDKD** [comment]
Let me know when you have it fixed and I will get out of Pro so you can get the fix into DEV  then I can check all the ARs for MIT that you recently updated.

**Comment by steveoh** [comment]
I can make the change in code and you could uncheck the insert box to continue testing if you'd like.

**Comment by CanDKD** [comment]
I can't uncheck insert because the view is read-only.
![image](https://user-images.githubusercontent.com/4369080/67513551-46fc3700-f658-11e9-9c81-c490aa87e534.png)
