### ISSUE TITLE
UIC Well ID Calculation

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#14]
WellID should be calculated as follows:

![image](https://user-images.githubusercontent.com/4369080/57393287-08dd8a80-7180-11e9-94ba-399867d7d421.png)

One of my test Class 1 wells has a WellID as follows:

![image](https://user-images.githubusercontent.com/4369080/57393770-0a5b8280-7181-11e9-9f2b-5a00859e0d42.png)

I think the '2' should be a '0'.  The rest of the ID looks correct.

**Comment by steveoh** [comment]
Ok, it looks like the fips was placed before the class.

https://github.com/agrc/uic-attribute-rules/blob/master/src/rules/well.py#L51

**Comment by CanDKD** [comment]
that's correct.   not sure where the '2' came from.

**Comment by steveoh** [comment]
23 is the fips code...

**Comment by CanDKD** [comment]
Here's a clip from our UICStateCountyFIPSDomain.  Last 2 digits of the FIPs for BoxElder County is '03'

![image](https://user-images.githubusercontent.com/4369080/57394693-5d363980-7183-11e9-8689-325840843b5d.png)

**Comment by steveoh** [comment]
I understand that. And I linked to this from the facility issue but it might not have made sense then. All wells are currently using the same geometry and will not have the county fips you expect.

https://github.com/agrc/uic-attribute-rules/blob/e2008ec367b175e69e0b46a3a09e436329b88f27/src/rules/well.py#L47

**Comment by CanDKD** [comment]
Table 'UICWell'; Field 'UIC Well ID' is not being autopopulated.  Not sure why it is not as it had been in the past.

**Comment by steveoh** [comment]
How many rules are disabled? Is this one of the disabled rules?

**Comment by CanDKD** [comment]
this rule is not disabled, I checked.  
UICWell: 3 ARs , none disabled
UICArtPen: 1 AR, not disabled
UICFacility: 6 ARs, none disabled
UICAreaOfReview: 1 AR, not disabled
UICAuthorization: 2 ARs, none disabled
UICAuthorizationAction: 1 AR, not disabled
UICContact: 1 AR, not disabled
UICCorrection: 1 AR, not disabled
UICEnforcement: 1 AR, not disabled
UICInspection: 1 AR, not disabled
UICMIT: 1 AR, not disabled
UICViolation: 2 ARs, not disabled
UICWellOperatingStatus: 1 AR, not disabled

**Comment by steveoh** [comment]
The old bug is not present in 2.4 and for the wellid to calculate the well class and sub class need to be set.
