### ISSUE TITLE
UICArtPen - Error Raised when Ident4CA field populated

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#17]
![image](https://user-images.githubusercontent.com/4369080/57708889-54cc7b80-7627-11e9-9907-a7bf7e2ac462.png)

Perhaps a constraint attribute rule isn't the best way to track UICArtPen wells that need corrective action.  I have already created 2 Definition Queries that will capture UICArtPen wells when the coded value for Ident4CA is 1.  The Pro interface allows one to Activate and Deactive saved Definition Queries fairly easily.

Flagging a UICArtPen for corrective action (Ident4CA = 1) will always happen before the actual corrective action is performed so this error will always be raised when Ident4CA is set to 'yes'.

**Comment by steveoh** [comment]
ok, this functionality could be moved to the add-in or we could look at validation rules. I believe validation rules are not feasible for your system though.

**Comment by CanDKD** [comment]
okay, Let's keep it simple.  As I recall, validation needed a server or something.

**Comment by steveoh** [comment]
We just updated the rules for these fields. Are you still wanting to remove the constraints from `ident4ca`? If you will be setting the field to yes and later adding the date and type then the rules should be removed as you will never be allowed to save the changes.

**Comment by CanDKD** [comment]
Yes remove it.  The ArtPen record can be created without this field being populated because it will take some time for the reviewer to determine whether or not the ArtPen well needs corrective action
