### ISSUE TITLE
Calculation of AuthorizationID is incorrect.

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#18]
I created an Authorization record.  It appears the AuthorizationID is not capturing the last 7 digits of the GUID

![image](https://user-images.githubusercontent.com/4369080/62229536-14a2ac80-b37d-11e9-8873-91e3bc07b0d3.png)

![image](https://user-images.githubusercontent.com/4369080/62229401-cab9c680-b37c-11e9-8785-56a89a80f743.png)

**Comment by steveoh** [comment]
closed by 7ec9fb9ec83ca2cb7e832fea8f1dcbdc45cabb44

**Comment by CanDKD** [comment]
Calculation of AuthorizationID is still off.

![image](https://user-images.githubusercontent.com/4369080/62392687-540bfd00-b525-11e9-82ed-9c0a7f2bb91e.png)

The digits from the GUID that are to be used to create the AuthoriztionID are the last **7** digits.

![image](https://user-images.githubusercontent.com/4369080/62393436-66873600-b527-11e9-8503-1517b6fdfa30.png)

I think the '29' in your code below needs to be '30' instead.

![image](https://user-images.githubusercontent.com/4369080/62393537-ae0dc200-b527-11e9-96e0-6a569f9c9b07.png)

**Comment by steveoh** [comment]
please check the facility version since it is the same...

`return 'UTU' + right($feature.countyfips, 2) + 'F' + upper(mid($feature.guid, 29, 8))`

**Comment by CanDKD** [comment]
FacilityID and AuthorizationID are different: 

![image](https://user-images.githubusercontent.com/4369080/62575879-edeee500-b858-11e9-9358-b5aef752972b.png)

**Comment by CanDKD** [comment]
I just noticed that I had this wrong in the Geodatabase Details pdf in Team drive  What you see above is correct
