### ISSUE TITLE
Remove Default Error Messages from Attribute Rules

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#21]
The default error messages clutter up the Arcade error message and take focus away from the actual cause of the error.

**Comment by steveoh** [comment]
I tried to remove the defaults and when adding the rules esri said woah, wait a minute...

> This attribute rule requires error number and message.

Maybe I can add an empty message when I sort out which rules **require** these **optional** parameters

**Comment by steveoh** [comment]
Constraint rules require an error number and message. I can make the message empty or I can add a note... Which do you prefer,

![image](https://user-images.githubusercontent.com/325813/62306626-6d3a7e00-b43f-11e9-9276-338bc89cdb9d.png)

or 

![image](https://user-images.githubusercontent.com/325813/62306699-90652d80-b43f-11e9-94fe-cceb2e9af593.png)

**Comment by steveoh** [comment]
I went with option 2 as it's cleaner
