### ISSUE TITLE
UICAuthorization.AuthorizationType  default

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#27]
Currently, the default value for this field is Unauthorized (NO). This is a placeholder value and needs to be changed to one of the other values in coded value domain.  The AR error message should  read:
AuthorizationType may not be Unauthorized (NO); select the appropriate value from the UICAuthorizeTypeDomain (dropdown menu).

**Comment by steveoh** [comment]
Do you want the default value updated?

**Comment by CanDKD** [comment]
you can leave it at Unauthorized because null isn't in the dropdown list
