### ISSUE TITLE
Constraint.Well.WellSWPZ caused a 'Failed to Create Feature' error

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#31]
After creating a new UICFaciltiy, I tried to add a new UICWell and got this error:

![image](https://user-images.githubusercontent.com/4369080/62390994-dd6d0080-b520-11e9-96ff-be42eb4ea556.png)

**Comment by CanDKD** [comment]
this is what that AR looks like in the Pro Project:
![image](https://user-images.githubusercontent.com/4369080/62391217-79970780-b521-11e9-99fc-dcf4653b046e.png)

**Comment by steveoh** [comment]
what do you want to happen? Should you be able to create a new well with an empty swpz?

**Comment by CanDKD** [comment]
After I create a UICFacility, I want to then be able to create a UICWell within that facility.  When I try to do that I get the error above.  This seems to be a new issue because I have been able to create wells within facilities before.
