### ISSUE TITLE
Constraint.Correction.Comment

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#35]
Select CorrectiveAction = OT with nothing in Comments field.  The error message appears as expected.   Enter Comment as required then hit Enter. The Apply button is not activated until I change CorrectiveAction to something else, Apply button is activated, hit Apply, then go back to change CorrectiveAction to OT. then save.

**Comment by steveoh** [comment]
I think this is a bug with esri. The data is valid but the apply button does not realize it. If you leave the attribute window and click to the map, it will ask you to apply to discard your changes and if you choose to apply them, they save properly. 

I have https://github.com/steveoh/esri-bugs/tree/master/02373754 as an open issue with esri so I will close this and hope that it will fix itself as we work through that issue.
