### ISSUE TITLE
Constraint.Violation.FacilityWellTypes

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#38]
This AR is preventing me from adding Violation records to either a well or a facility.

![image](https://user-images.githubusercontent.com/4369080/62401026-a6a5e300-b53e-11e9-9919-56e4a39c04a8.png)

**Comment by CanDKD** [comment]
I think this issue may be similar to issue 10 in that the record can have one or the other but not both Well_FK or Facility_FK

**Comment by steveoh** [comment]
probably. You'll have to disable the insert trigger to move forward.

refs #10
