### ISSUE TITLE
Move FacilityType from UICFacility to UICWell

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#4]
This parameter is more closely related to the well than the facility.  It will probably be much easier to deal with the constraint that it must be populated when the WellClass = 1

**Comment by steveoh** [comment]
Based on the name, I'm not sure I agree with this one... Should we rename the field? The domain is commercial/non commercial so maybe it really isn't that related to the facility.

**Comment by CanDKD** [comment]
Let me explain this field.  Class I wells can be used by a private company to dispose of their liquid waste (non-commercial) or a company can operate a Class I well and receive liquid waste from other facilities (commercial) that do not have or choose to operate a Class I well.  The focus is really on the Class I well.   We could rename the fields ClassIFacilityType.  I thought it might be easier to code the constraint rule if the field was in the UICWell attribute table.
