### ISSUE TITLE
Constraint.ArtPen.ArtPen_CADate

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#44]
ArtPen_CADate cannot be empty if ArtPen_CAType has a value  NOT if Ident4CA has a value.  These 2 values will be entered at the same time; at a time after Ident4CA is set.

![image](https://user-images.githubusercontent.com/4369080/62496811-55dcf700-b797-11e9-9d2e-6ab34941568f.png)

**Comment by steveoh** [comment]
is this an issue with the rule or the error message text?

**Comment by CanDKD** [comment]
I think this is an issue with the rule and the error message 
I think the following code should check for ArtPen_CAType NOT Ident4CA and the error message should be 'ArtPen_CADate cannot be empty when ArtPen_CAType has a value'

return iif (isempty($feature.artpen_cadate), {
    'errorMessage': 'ArtPen_CADate cannot be empty when Ident4CA has a value'
}, true);

**Comment by CanDKD** [comment]
This Issue #44 is evolving.  The error fires after I have entered an ArtPen_WellName as below:

**Comment by CanDKD** [comment]
![image](https://user-images.githubusercontent.com/4369080/62644062-842d1480-b906-11e9-80ab-5d5248a0be18.png)
