### ISSUE TITLE
Generation of AuthorizationID

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#5]
Responding to a question in the UIC GDB Fields and AR doc.
UTUCCAAXXXXXXX
CC = 2 digit CountyFIPS code of associated Facility
AA = 2 digit AuthorizationType code where:
>RA = Rule Authorized
>IP = Individual Permit
>AP=Area Permit
>GP=General Permit
>EP=Emergency Permit
>UA = Unauthorized
XXXXXXX = right seven digits of the AuthorizationID GUID

**Comment by steveoh** [comment]
Unauthorized in the AuthorizationType domain is set to NO. Should that be updated to UA?

**Comment by CanDKD** [comment]
Y es,UA is the default

**Comment by steveoh** [comment]
So the current NO should be replaced with UA or should the rule handle the discrepancy and use UA instead of NO for that domain value?

**Comment by CanDKD** [comment]
the Authorization code for Unauthorized is NO (that was EPA's code back in
the day).  I was wrong when I said the default was UA, there is not code UA
even though it makes more sense than NO.  I don't want to re-write the
coded value domain, so let's stick with NO as default
