### ISSUE TITLE
List of fields that cannot be empty

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-attribute-rules#50]
### Well

- [x] UICWell.WellName on insert or update

### Facility

- [x] UICFacility.FacilityName on insert or update
- [x] UICFacility.FacilityAddress on insert or update

### Area Of Review

- [x] UICAreaOfReview.Authorization_FK on update

### Art Pen

- [x] UICArtPen.ArtPen_WellName on insert or update

### Authorization

- [x] UICAuthorization.StartDate on insert or update:

### Contact

- [x] UICContact.ContactName
- [x] ContactOrganization
- [x] ContactMailAddress
- [x] ContactMailCity
- [x] ContactMailState

### MIT

- [x] UICMIT.MITDate
- [x] MITResult on insert or update

**Comment by CanDKD** [comment]
Other fields that should not be empty: 
UICWell.WellName  on insert or update:
UICFacility.FacilityName  on insert or update:
UICFacility.FacilityAddress  on insert or update:
UICAreaOfReview.Authorization_FK  on update
UICArtPen.ArtPen_WellName  on insert or update:
UICArtPen.Artpen_ReviewDate on update  this field needs to be married to Ident4CA, these fields need to be entered at the same time
UICAuthorization.StartDate  on insert or update:
UICContact.ContactName, ContactOrganization, ContactMailAddress, ContactMailCity, ContactMailState, ContactMailState
UICMIT.MITDate, MITResult  on insert or update:
UICMIT. MITRemediationAction and MITRemActDate need to be entered at the same time on update
