### ISSUE TITLE
Problem with UICAreaOfReview to UICArtPen Relationship

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#6]
Problem with UICArtPen.  I thought Michael and I had implemented a 1 to Many relationship from UICAreaOfReview to UICArtPen.  But this would imply to me that UICArtPen should have an UICAreaOfReview_FK.  It doesn't.    We tried to implement a Many to Many relationship because Areas of Review could overlap sharing some ArtPens.  But we couldn't get that to happen.  However, the fact that UICArpPen doesn't have an FK back to UICAreaOfReview makes me think that a bridging table exists.

**Comment by steveoh** [comment]
What would you like me to do here?

**Comment by CanDKD** [comment]
This may not be something you can help me with; more likely Michael. I just wanted to put this issue some place to document it.  There are 2 fields I want to add to the UICArtPen table: AOR_FK and ArtPenWellDepth.  Once I have done that, I think I need to delete the current relationship between UICAreaOfReview table and UICArtPen table then completely rebuild a relationship class with a 1 to Many cardinality  from AOR to ArtPen.  But before I do that I think I need to compress and unregister as versioned (this is all being done in DEV) so as to delete any delta tables.  This is where I need to talk to Michael to make sure I have all the steps figured out.

**Comment by CanDKD** [comment]
I was able to create a M-N relationship in DEV between UICAuthorization and UICArtPen
