### ISSUE TITLE
Restrict ViolationType codes for Well and Facility 

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#9]
Line 142 of GDB Fields and AR doc

Allowable ViolationType codes for:

Facility violations: OM, MR, FO, FA, FI, FR, OT
Well violations: UI, OM, PA, MR, IP, FO, FA, FR, MI, MO, OT 

If a contingent value list could be based on whether or not Facility_FK was populated or not that would be handy.  If Facility_FK != Null then only Facility violations list would show up in the ViolationType dropdown list.. Same for Well_FK

**Comment by steveoh** [comment]
If the relationship is M*M then yes. Otherwise I can do it now.

**Comment by CanDKD** [comment]
Facility to Violation is ONe to Many

**Comment by steveoh** [comment]
I am not able to create a contingency on guid field types. I will create a constraint instead if that is ok?
