### ISSUE TITLE
Re-Enabling Editor Tracking Adds 4 Fields

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-attribute-rules#98]
Have re-enabled editor tracking for the attribute tables and standalone tables in the gdb.   Pro adds the default fields which are now populated but the custom fields CreatedOn, CreatedBy, ModifiedOn and EditedBy are not populated.  If this is likely to be an ongoing problem as we switch back and for during development, we can just stick with the default fields.

![image](https://user-images.githubusercontent.com/4369080/62963942-378e8100-bdbf-11e9-800f-fde7c9924b04.png)

**Comment by steveoh** [comment]
This is an issue with how you enabled the editor tracking. The [migration script](https://github.com/agrc/uic-attribute-rules/blob/master/src/migrations.py#L200-L208) reuses the "custom fields"

**Comment by CanDKD** [comment]
ok, so I'm not going to worry about it then.
